# Gradle Properties
org.gradle.jvmargs = -Xmx2G
# org.gradle.configuration-cache=true
org.gradle.parallel = true

# Mod Properties
version = 0.1.0
maven_group = net.librebounce
archives_base_name = librebounce

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.8.9
loader_version = 0.19.3

feather_build = 1

fabric_kotlin_version=1.13.12+kotlin.2.4.0

osl_version = 0.20.3

joml_version = 1.10.9
